export const paisList = [
    { value: "Afganistán", label: "Afganistán"},
	{ value: "Albania", label: "Albania"},
	{ value: "Alemania", label: "Alemania"},
	{ value: "Andorra", label: "Andorra"},
	{ value: "Angola", label: "Angola"},
	{ value: "Anguilla", label: "Anguilla"},
	{ value: "Antártida", label: "Antártida"},
	{ value: "Antigua y Barbuda", label: "Antigua y Barbuda"},
	{ value: "Antillas Holandesas", label: "Antillas Holandesas"},
	{ value: "Arabia Saudí", label: "Arabia Saudí"},
	{ value: "Argelia", label: "Argelia"},
	{ value: "Argentina", label: "Argentina", selected: true},
	{ value: "Armenia", label: "Armenia"},
	{ value: "Aruba", label: "Aruba"},
	{ value: "Australia", label: "Australia"},
	{ value: "Austria", label: "Austria"},
	{ value: "Azerbaiyán", label: "Azerbaiyán"},
	{ value: "Bahamas", label: "Bahamas"},
	{ value: "Bahrein", label: "Bahrein"},
	{ value: "Bangladesh", label: "Bangladesh"},
	{ value: "Barbados", label: "Barbados"},
	{ value: "Bélgica", label: "Bélgica"},
	{ value: "Belice", label: "Belice"},
	{ value: "Benin", label: "Benin"},
	{ value: "Bermudas", label: "Bermudas"},
	{ value: "Bielorrusia", label: "Bielorrusia"},
	{ value: "Birmania", label: "Birmania"},
	{ value: "Bolivia", label: "Bolivia"},
	{ value: "Bosnia y Herzegovina", label: "Bosnia y Herzegovina"},
	{ value: "Botswana", label: "Botswana"},
	{ value: "Brasil", label: "Brasil"},
	{ value: "Brunei", label: "Brunei"},
	{ value: "Bulgaria", label: "Bulgaria"},
	{ value: "Burkina Faso", label: "Burkina Faso"},
	{ value: "Burundi", label: "Burundi"},
	{ value: "Bután", label: "Bután"},
	{ value: "Cabo Verde", label: "Cabo Verde"},
	{ value: "Camboya", label: "Camboya"},
	{ value: "Camerún", label: "Camerún"},
	{ value: "Canadá", label: "Canadá"},
	{ value: "Chad", label: "Chad"},
	{ value: "Chile", label: "Chile"},
	{ value: "China", label: "China"},
	{ value: "Chipre", label: "Chipre"},
	{ value: "Ciudad del Vaticano (Santa Sede)", label: "Ciudad del Vaticano (Santa Sede)"},
	{ value: "Colombia", label: "Colombia"},
	{ value: "Comores", label: "Comores"},
	{ value: "Congo", label: "Congo"},
	{ value: "Congo, República Democrática del", label: "Congo, República Democrática del"},
	{ value: "Corea", label: "Corea"},
	{ value: "Corea del Norte", label: "Corea del Norte"},
	{ value: "Costa de Marfíl", label: "Costa de Marfíl"},
	{ value: "Costa Rica", label: "Costa Rica"},
	{ value: "Croacia (Hrvatska)", label: "Croacia (Hrvatska)"},
	{ value: "Cuba", label: "Cuba"},
	{ value: "Dinamarca", label: "Dinamarca"},
	{ value: "Djibouti", label: "Djibouti"},
	{ value: "Dominica", label: "Dominica"},
	{ value: "Ecuador", label: "Ecuador"},
	{ value: "Egipto", label: "Egipto"},
	{ value: "El Salvador", label: "El Salvador"},
	{ value: "Emiratos Árabes Unidos", label: "Emiratos Árabes Unidos"},
	{ value: "Eritrea", label: "Eritrea"},
	{ value: "Eslovenia", label: "Eslovenia"},
	{ value: "España", label: "España"},
	{ value: "Estados Unidos", label: "Estados Unidos"},
	{ value: "Estonia", label: "Estonia"},
	{ value: "Etiopía", label: "Etiopía"},
	{ value: "Fiji", label: "Fiji"},
	{ value: "Filipinas", label: "Filipinas"},
	{ value: "Finlandia", label: "Finlandia"},
	{ value: "Francia", label: "Francia"},
	{ value: "Gabón", label: "Gabón"},
	{ value: "Gambia", label: "Gambia"},
	{ value: "Georgia", label: "Georgia"},
	{ value: "Ghana", label: "Ghana"},
	{ value: "Gibraltar", label: "Gibraltar"},
	{ value: "Granada", label: "Granada"},
	{ value: "Grecia", label: "Grecia"},
	{ value: "Groenlandia", label: "Groenlandia"},
	{ value: "Guadalupe", label: "Guadalupe"},
	{ value: "Guam", label: "Guam"},
	{ value: "Guatemala", label: "Guatemala"},
	{ value: "Guayana", label: "Guayana"},
	{ value: "Guayana Francesa", label: "Guayana Francesa"},
	{ value: "Guinea", label: "Guinea"},
	{ value: "Guinea Ecuatorial", label: "Guinea Ecuatorial"},
	{ value: "Guinea-Bissau", label: "Guinea-Bissau"},
	{ value: "Haití", label: "Haití"},
	{ value: "Honduras", label: "Honduras"},
	{ value: "Hungría", label: "Hungría"},
	{ value: "India", label: "India"},
	{ value: "Indonesia", label: "Indonesia"},
	{ value: "Irak", label: "Irak"},
	{ value: "Irán", label: "Irán"},
	{ value: "Irlanda", label: "Irlanda"},
	{ value: "Isla Bouvet", label: "Isla Bouvet"},
	{ value: "Isla de Christmas", label: "Isla de Christmas"},
	{ value: "Islandia", label: "Islandia"},
	{ value: "Islas Caimán", label: "Islas Caimán"},
	{ value: "Islas Cook", label: "Islas Cook"},
	{ value: "Islas de Cocos o Keeling", label: "Islas de Cocos o Keeling"},
	{ value: "Islas Faroe", label: "Islas Faroe"},
	{ value: "Islas Heard y McDonald", label: "Islas Heard y McDonald"},
	{ value: "Islas Malvinas", label: "Islas Malvinas"},
	{ value: "Islas Marianas del Norte", label: "Islas Marianas del Norte"},
	{ value: "Islas Marshall", label: "Islas Marshall"},
	{ value: "Islas menores de Estados Unidos", label: "Islas menores de Estados Unidos"},
	{ value: "Islas Palau", label: "Islas Palau"},
	{ value: "Islas Salomón", label: "Islas Salomón"},
	{ value: "Islas Svalbard y Jan Mayen", label: "Islas Svalbard y Jan Mayen"},
	{ value: "Islas Tokelau", label: "Islas Tokelau"},
	{ value: "Islas Turks y Caicos", label: "Islas Turks y Caicos"},
	{ value: "Islas Vírgenes (EEUU)", label: "Islas Vírgenes (EEUU)"},
	{ value: "Islas Vírgenes (Reino Unido)", label: "Islas Vírgenes (Reino Unido)"},
	{ value: "Islas Wallis y Futuna", label: "Islas Wallis y Futuna"},
	{ value: "Israel", label: "Israel"},
	{ value: "Italia", label: "Italia"},
	{ value: "Jamaica", label: "Jamaica"},
	{ value: "Japón", label: "Japón"},
	{ value: "Jordania", label: "Jordania"},
	{ value: "Kazajistán", label: "Kazajistán"},
	{ value: "Kenia", label: "Kenia"},
	{ value: "Kirguizistán", label: "Kirguizistán"},
	{ value: "Kiribati", label: "Kiribati"},
	{ value: "Kuwait", label: "Kuwait"},
	{ value: "Laos", label: "Laos"},
	{ value: "Lesotho", label: "Lesotho"},
	{ value: "Letonia", label: "Letonia"},
	{ value: "Líbano", label: "Líbano"},
	{ value: "Liberia", label: "Liberia"},
	{ value: "Libia", label: "Libia"},
	{ value: "Liechtenstein", label: "Liechtenstein"},
	{ value: "Lituania", label: "Lituania"},
	{ value: "Luxemburgo", label: "Luxemburgo"},
	{ value: "Macedonia, Ex-República Yugoslava de", label: "Macedonia, Ex-República Yugoslava de"},
	{ value: "Madagascar", label: "Madagascar"},
	{ value: "Malasia", label: "Malasia"},
	{ value: "Malawi", label: "Malawi"},
	{ value: "Maldivas", label: "Maldivas"},
	{ value: "Malí", label: "Malí"},
	{ value: "Malta", label: "Malta"},
	{ value: "Marruecos", label: "Marruecos"},
	{ value: "Martinica", label: "Martinica"},
	{ value: "Mauricio", label: "Mauricio"},
	{ value: "Mauritania", label: "Mauritania"},
	{ value: "Mayotte", label: "Mayotte"},
	{ value: "México", label: "México"},
	{ value: "Micronesia", label: "Micronesia"},
	{ value: "Moldavia", label: "Moldavia"},
	{ value: "Mónaco", label: "Mónaco"},
	{ value: "Mongolia", label: "Mongolia"},
	{ value: "Montserrat", label: "Montserrat"},
	{ value: "Mozambique", label: "Mozambique"},
	{ value: "Namibia", label: "Namibia"},
	{ value: "Nauru", label: "Nauru"},
	{ value: "Nepal", label: "Nepal"},
	{ value: "Nicaragua", label: "Nicaragua"},
	{ value: "Níger", label: "Níger"},
	{ value: "Nigeria", label: "Nigeria"},
	{ value: "Niue", label: "Niue"},
	{ value: "Norfolk", label: "Norfolk"},
	{ value: "Noruega", label: "Noruega"},
	{ value: "Nueva Caledonia", label: "Nueva Caledonia"},
	{ value: "Nueva Zelanda", label: "Nueva Zelanda"},
	{ value: "Omán", label: "Omán"},
	{ value: "Países Bajos", label: "Países Bajos"},
	{ value: "Panamá", label: "Panamá"},
	{ value: "Papúa Nueva Guinea", label: "Papúa Nueva Guinea"},
	{ value: "Paquistán", label: "Paquistán"},
	{ value: "Paraguay", label: "Paraguay"},
	{ value: "Perú", label: "Perú"},
	{ value: "Pitcairn", label: "Pitcairn"},
	{ value: "Polinesia Francesa", label: "Polinesia Francesa"},
	{ value: "Polonia", label: "Polonia"},
	{ value: "Portugal", label: "Portugal"},
	{ value: "Puerto Rico", label: "Puerto Rico"},
	{ value: "Qatar", label: "Qatar"},
	{ value: "Reino Unido", label: "Reino Unido"},
	{ value: "República Centroafricana", label: "República Centroafricana"},
	{ value: "República Checa", label: "República Checa"},
	{ value: "República de Sudáfrica", label: "República de Sudáfrica"},
	{ value: "República Dominicana", label: "República Dominicana"},
	{ value: "República Eslovaca", label: "República Eslovaca"},
	{ value: "Reunión", label: "Reunión"},
	{ value: "Ruanda", label: "Ruanda"},
	{ value: "Rumania", label: "Rumania"},
	{ value: "Rusia", label: "Rusia"},
	{ value: "Sahara Occidental", label: "Sahara Occidental"},
	{ value: "Saint Kitts y Nevis", label: "Saint Kitts y Nevis"},
	{ value: "Samoa", label: "Samoa"},
	{ value: "Samoa Americana", label: "Samoa Americana"},
	{ value: "San Marino", label: "San Marino"},
	{ value: "San Vicente y Granadinas", label: "San Vicente y Granadinas"},
	{ value: "Santa Helena", label: "Santa Helena"},
	{ value: "Santa Lucía", label: "Santa Lucía"},
	{ value: "Santo Tomé y Príncipe", label: "Santo Tomé y Príncipe"},
	{ value: "Senegal", label: "Senegal"},
	{ value: "Seychelles", label: "Seychelles"},
	{ value: "Sierra Leona", label: "Sierra Leona"},
	{ value: "Singapur", label: "Singapur"},
	{ value: "Siria", label: "Siria"},
	{ value: "Somalia", label: "Somalia"},
	{ value: "Sri Lanka", label: "Sri Lanka"},
	{ value: "St Pierre y Miquelon", label: "St Pierre y Miquelon"},
	{ value: "Suazilandia", label: "Suazilandia"},
	{ value: "Sudán", label: "Sudán"},
	{ value: "Suecia", label: "Suecia"},
	{ value: "Suiza", label: "Suiza"},
	{ value: "Surinam", label: "Surinam"},
	{ value: "Tailandia", label: "Tailandia"},
	{ value: "Taiwán", label: "Taiwán"},
	{ value: "Tanzania", label: "Tanzania"},
	{ value: "Tayikistán", label: "Tayikistán"},
	{ value: "Territorios franceses del Sur", label: "Territorios franceses del Sur"},
	{ value: "Timor Oriental", label: "Timor Oriental"},
	{ value: "Togo", label: "Togo"},
	{ value: "Tonga", label: "Tonga"},
	{ value: "Trinidad y Tobago", label: "Trinidad y Tobago"},
	{ value: "Túnez", label: "Túnez"},
	{ value: "Turkmenistán", label: "Turkmenistán"},
	{ value: "Turquía", label: "Turquía"},
	{ value: "Tuvalu", label: "Tuvalu"},
	{ value: "Ucrania", label: "Ucrania"},
	{ value: "Uganda", label: "Uganda"},
	{ value: "Uruguay", label: "Uruguay"},
	{ value: "Uzbekistán", label: "Uzbekistán"},
	{ value: "Vanuatu", label: "Vanuatu"},
	{ value: "Venezuela", label: "Venezuela"},
	{ value: "Vietnam", label: "Vietnam"},
	{ value: "Yemen", label: "Yemen"},
	{ value: "Yugoslavia", label: "Yugoslavia"},
	{ value: "Zambia", label: "Zambia"},
	{ value: "Zimbabue", label: "Zimbabue"},
];

export const estadoCivilList = [ 
  {
    value: 'SOLTERO',
    label: 'Soltero/a',
  },
  {
    value: 'CASADO',
    label: 'Casado/a',
  },{
    value: 'DIVORCIADO',
    label: 'Divorciado/a',
  },
  {
    value: 'VIUDO',
    label: 'Viudo/a',
  },
];